export const TRIAGE_PHRASES = {
  approveDraft: ['draft statement', 'final statement', 'final version', 'ceo quote', 'quote for', 'unless you object'],
  ceoDecision: [
    'needs your signature',
    'still need signature',
    'not signed',
    'need you on',
    'can you have',
    'can you also',
    'would you prefer',
    'review before',
    'please review',
    'recommend we move',
    'move on an offer',
    'your ok',
    'align on a response',
    'confirm or deny',
    'checking in',
    'need a decision',
    'one more thing',
    'confirm ceo has seen',
    'does the board chair have',
  ],
  later: ['reminder', 'by friday', 'no rush', 'no urgency', 'early bird'],
};

export const CATEGORY_LABELS = {
  SECURITY_RISK: 'Security risk',
  CEO_DECISION: 'Needs your decision',
  APPROVE_DRAFT: 'Approve a draft',
  AUTO_HANDLED: 'Handled by StandIn',
  LATER: 'Later',
  FYI: 'FYI',
  NOISE: 'Noise',
};
